use std::env;
use std::io::ErrorKind::BrokenPipe;
use std::io::{stdout, Write};

struct Tld(&'static str, &'static str, &'static str, &'static str);

static TLD_DATA: &[Tld] = &[
    Tld(".ac", "Ascension Island (United Kingdom)", "Ascension Island", "Commonly used for academic websites, such as universities. However, .ac is not to be confused with the official academic domains used by several countries such as the United Kingdom (.ac.uk), India (.ac.in) or Indonesia (.ac.id). Also used in the accounting, consulting, and air-conditioning industries."),
    Tld(".ad", "Andorra", "Andorra", "Local trademark, trade name or citizenship required"),
    Tld(".ae", "United Arab Emirates", "United Arab Emirates", ""),
    Tld(".af", "Afghanistan", "Afghanistan", ""),
    Tld(".ag", "Antigua and Barbuda", "Antigua and Barbuda", "Also unofficially used by German businesses (where AG is an abbreviation of Aktiengesellschaft)."),
    Tld(".ai", "Anguilla (United Kingdom)", "Anguilla", "Also unofficially used by tech companies specializing in AI (Artificial Intelligence)."),
    Tld(".al", "Albania", "Albania", "Citizenship no longer required."),
    Tld(".am", "Armenia", "Armenia", "Also unofficially used by AM radio stations, podcasts or related business."),
    Tld(".ao", "Angola", "Angola", ""),
    Tld(".aq", "Antarctica", "Antarctique", "Defined by the Antarctic Treaty as everything south of latitude 60°S. AQ domain names are available to government organizations who are signatories to the Antarctic Treaty and to other registrants who have a physical presence in Antarctica. Domain names can be registered and renewed free of charge."),
    Tld(".ar", "Argentina", "Argentina", ""),
    Tld(".as", "American Samoa (United States)", "American Samoa", "In some countries, like Norway and Denmark, \"AS\" or \"A/S\" is used as an abbreviation for stock-based or limited companies. Such companies will often make use of the domain. Also unofficially used by the Principality of Asturias, Spain."),
    Tld(".at", "Austria", "Austria", ""),
    Tld(".au", "Australia", "Australia", "Restrictions apply. In general, registrants must have an \"Australian presence\", and can be registered anywhere between 1 and 5 years. Includes Ashmore and Cartier Islands and Coral Sea Islands. Direct second-level domain registration (marketed as \".au Direct\") has been made available commencing 24 March 2022."),
    Tld(".aw", "Aruba (Kingdom of the Netherlands)", "Aruba, West Indies", "Restricted to registered Aruban companies, organisations and citizens"),
    Tld(".ax", "Åland (Finland)", ".al and .ad already allocated", ""),
    Tld(".az", "Azerbaijan", "Azerbaijan", "Only for Residents. Has no WHOIS-Server."),
    Tld(".ba", "Bosnia and Herzegovina", "Bosnia and Herzegovina", ""),
    Tld(".bb", "Barbados", "Barbados", ""),
    Tld(".bd", "Bangladesh", "Bangladesh", "For individuals, registrant must have a valid NID. For companies, registrant must have company or trademark registered in Bangladesh."),
    Tld(".be", "Belgium", "Belgium", "Used for YouTube-related domains. Also unofficially used in the Canton of Bern, Switzerland."),
    Tld(".bf", "Burkina Faso", "Burkina Faso", ""),
    Tld(".bg", "Bulgaria", "Bulgaria", "See also .бг (.bg in Cyrillic) for IDN ccTLD"),
    Tld(".bh", "Bahrain", "Bahrain", ""),
    Tld(".bi", "Burundi", "Burundi", ""),
    Tld(".bj", "Benin", ".be, .bn, and .bi already allocated", ""),
    Tld(".bm", "Bermuda (United Kingdom)", "Bermuda", "Local corporate registration required"),
    Tld(".bn", "Brunei", "Brunei", ""),
    Tld(".bo", "Bolivia", "Bolivia", ""),
    Tld(".bq", "Caribbean Netherlands ( Bonaire,  Saba, and  Sint Eustatius)", ".be and .bs already allocated", ""),
    Tld(".br", "Brazil", "Brasil", "Restricted. Registration is done under several categories (i.e.: .edu.br for higher education institutions, .gov.br for government agencies, etc.)."),
    Tld(".bs", "Bahamas", "Bahamas", ""),
    Tld(".bt", "Bhutan", "Bhutan", "Must have local presence in Bhutan, and valid trade license"),
    Tld(".bw", "Botswana", "Botswana", "May also be used for the Province of Walloon Brabant, Wallonia, Belgium"),
    Tld(".by", "Belarus", "Byelorussia", "Also unofficially used to denote Bayern (Bavaria), Germany"),
    Tld(".bz", "Belize", "Belize", "Also unofficially used in the province of Bozen (or South Tyrol, see .st)"),
    Tld(".ca", "Canada", "Canada", "Subject to Canadian Presence Requirements. Also unofficially used by some websites in the U.S. state of California."),
    Tld(".cc", "Cocos (Keeling) Islands", "Cocos Islands", "Australian territory: not to be confused with Cocos Island in Guam. Currently marketed as global domain, registration allowed worldwide, local presence not required; the domain is currently operated by eNIC, a VeriSign company."),
    Tld(".cd", "Democratic Republic of the Congo", "Congo, Democratic Republic", "Also unofficially used for Compact disc-related domains."),
    Tld(".cf", "Central African Republic", "Central African Republic", "Also used as a free domain service to the public."),
    Tld(".cg", "Republic of the Congo", "Congo", ""),
    Tld(".ch", "Switzerland", "Confoederatio Helvetica", ""),
    Tld(".ci", "Ivory Coast", "Côte d'Ivoire", ""),
    Tld(".ck", "Cook Islands", "Cook Islands", ""),
    Tld(".cl", "Chile", "Chile", ""),
    Tld(".cm", "Cameroon", "Cameroon", "A local entity / company in Cameroon is required to register a domain name."),
    Tld(".cn", "People's Republic of China", "China", "A local company in China is required to register a domain name, or for personal registrations a valid Resident Identity Card. See ICP license for more information regarding registrations. Hong Kong and Macau also maintain TLDs."),
    Tld(".co", "Colombia", "Colombia", "Marketed as a global domain. Anyone can register."),
    Tld(".cr", "Costa Rica", "Costa Rica", ""),
    Tld(".cu", "Cuba", "Cuba", ""),
    Tld(".cv", "Cape Verde", "Cape Verde", "Also unofficially used for curriculum vitae-related domains."),
    Tld(".cw", "Curaçao (Kingdom of the Netherlands)", "Curaçao, West Indies", ""),
    Tld(".cx", "Christmas Island", "Christmas Xmas", "Made infamous from Goatse.cx"),
    Tld(".cy", "Cyprus", "Cyprus", ""),
    Tld(".cz", "Czech Republic", "Czech", ""),
    Tld(".de", "Germany", "Deutschland (The native name for Germany)", "German postal address for administrative contact (admin-c) required. Proxy registrations are allowed."),
    Tld(".dj", "Djibouti", "Djibouti", "Also unofficially used by disc jockeys."),
    Tld(".dk", "Denmark", "Danmark", ""),
    Tld(".dm", "Dominica", "Dominica", ""),
    Tld(".do", "Dominican Republic", "Dominican", ""),
    Tld(".dz", "Algeria", "El Djazair / Dzayer", ""),
    Tld(".ec", "Ecuador", "Ecuador", "In Japan, \"EC\" is used as an acronym for \"electronic commerce\". Because of that, it's used unofficially by companies dedicated to provide online stores like BASE, a company that has two domains related to e-commerce: \"base.in\" and \"official.ec\"."),
    Tld(".ee", "Estonia", "Eesti", ""),
    Tld(".eg", "Egypt", "Egypt", ""),
    Tld(".eh", "Western Sahara", "Español Sahara", "Unassigned"),
    Tld(".er", "Eritrea", "Eritrea", ""),
    Tld(".es", "Spain", "España", ""),
    Tld(".et", "Ethiopia", "Ethiopia", ""),
    Tld(".eu", "European Union", "European Union", "Restricted to legal and natural persons in European Union member states. Previously unofficially used for sites in the Basque language, but now .eus is in official use."),
    Tld(".fi", "Finland", "Finland", "Registration allowed worldwide, local presence not required."),
    Tld(".fj", "Fiji", "Fiji", ""),
    Tld(".fk", "Falkland Islands (United Kingdom)", "Falkland", ""),
    Tld(".fm", "Federated States of Micronesia", "Federated States of Micronesia", "Also unofficially used by FM radio stations, podcasts or related business."),
    Tld(".fo", "Faroe Islands (Kingdom of Denmark)", "Føroyar", ""),
    Tld(".fr", "France", "France", "Restricted to individuals and companies in European Union, Switzerland, Norway, Iceland and Liechtenstein."),
    Tld(".ga", "Gabon", "Gabon", "Also used as a free domain service to the public."),
    Tld(".gd", "Grenada", "Grenada", ""),
    Tld(".ge", "Georgia", "Georgia", "Available for registration for residents of Georgia (unlimited) or for foreign companies via representation of any local legal person (one domain name per registrant)."),
    Tld(".gf", "French Guiana (France)", "Guyane Française", ""),
    Tld(".gg", "Guernsey", ".gu, .gs, and .gy already allocated", "Also unofficially used by video game-related websites (see GG (gaming))"),
    Tld(".gh", "Ghana", "Ghana", ""),
    Tld(".gi", "Gibraltar (United Kingdom)", "Gibraltar", ""),
    Tld(".gl", "Greenland (Kingdom of Denmark)", "Greenland", "Previously also unofficially used in Galicia, Spain, but now .gal has been approved for such use and was implemented in mid-2014"),
    Tld(".gm", "The Gambia", "Gambia", "Domain name should match the domain owner's name or trademarks. Common nouns are blocked."),
    Tld(".gn", "Guinea", "Guinea", "A local contact is required"),
    Tld(".gp", "Guadeloupe (France)", "Guadeloupe", "Still used for Saint-Barthélemy and Saint-Martin"),
    Tld(".gq", "Equatorial Guinea", "Guinée équatoriale", "Also used as a free domain service to the public."),
    Tld(".gr", "Greece", "Greece", ""),
    Tld(".gs", "South Georgia and the South Sandwich Islands (United Kingdom)", "South Georgia and the South Sandwich Islands", ""),
    Tld(".gt", "Guatemala", "Guatemala", ""),
    Tld(".gu", "Guam (United States)", "Guam", ""),
    Tld(".gw", "Guinea-Bissau", "Gine-Bisaawo", ""),
    Tld(".gy", "Guyana", "Guyana", ""),
    Tld(".hk", "Hong Kong", "Hong Kong", ""),
    Tld(".hm", "Heard Island and McDonald Islands", "Heard Island and McDonald Islands", "Unused for its intended purposes (islands are uninhabited and government sites instead use .aq); registry open to the public."),
    Tld(".hn", "Honduras", "Honduras", ""),
    Tld(".hr", "Croatia", "Hrvatska", ""),
    Tld(".ht", "Haiti", "Haiti", ""),
    Tld(".hu", "Hungary", "Hungary", "Citizens of the European Union or entities established by law within the territory of the EU"),
    Tld(".id", "Indonesia", "Indonesia", "Restricted to Indonesian companies (co.id), organisations (or.id), academic (ac.id & sch.id) and citizens (biz.id, my.id & web.id). Second-level domains are becoming available now and opened to general registration on 17 August 2014."),
    Tld(".ie", "Ireland", "Ireland", "In 2002, registration was expanded to include persons or businesses with a \"real and substantive\" connection with the island of Ireland (including Northern Ireland)."),
    Tld(".il", "Israel", "Israel", ""),
    Tld(".im", "Isle of Man", "Isle of Man", ""),
    Tld(".in", "India", "India", "Under INRegistry since April 2005 (except for gov.in, nic.in, mil.in, ac.in, edu.in, res.in)."),
    Tld(".io", "British Indian Ocean Territory (United Kingdom)", "Indian Ocean", "Used unofficially by technology companies, startups, and web applications because IO can be an acronym for input / output that is useful for domain hacks."),
    Tld(".iq", "Iraq", "Iraq", ""),
    Tld(".ir", "Iran", "Iran", ""),
    Tld(".is", "Iceland", "Ísland", "Also unofficially used and marketed as a domain hack (for example it.is, that.is, etc.)."),
    Tld(".it", "Italy", "Italy", "Restricted to companies and individuals in the European Union."),
    Tld(".je", "Jersey", "Jersey", ""),
    Tld(".jm", "Jamaica", "Jamaica", ""),
    Tld(".jo", "Jordan", "Jordan", ""),
    Tld(".jp", "Japan", "Japan", "Restricted to individuals or companies with a physical address in Japan."),
    Tld(".ke", "Kenya", "Kenya", ""),
    Tld(".kg", "Kyrgyzstan", "Kyrgyzstan", ""),
    Tld(".kh", "Cambodia", "Khmer", ""),
    Tld(".ki", "Kiribati", "Kiribati", ""),
    Tld(".km", "Comoros", "Komori", ""),
    Tld(".kn", "Saint Kitts and Nevis", "Saint Kitts and Nevis", ""),
    Tld(".kp", "North Korea", "Korea, Democratic People's Republic", "Restricted to companies, organizations, or government entities based in North Korea. Despite this, few domains are actually registered because of internet censorship in North Korea."),
    Tld(".kr", "South Korea", "Korea, Republic", ""),
    Tld(".kw", "Kuwait", "Kuwait", ""),
    Tld(".ky", "Cayman Islands (United Kingdom)", ".ci and .cy already allocated", ""),
    Tld(".kz", "Kazakhstan", "Kazakhstan", ""),
    Tld(".la", "Laos", "Laos", "Currently being marketed as the unofficial domain for Los Angeles."),
    Tld(".lb", "Lebanon", "Lebanon", "Restricted to registration with a company in Lebanon"),
    Tld(".lc", "Saint Lucia", "Saint Lucia", ""),
    Tld(".li", "Liechtenstein", "Liechtenstein", "Also unofficially used by entities on Long Island, New York or people with the last name Li. In Russian, li can be used to create domain names that mean a verb with a past tense plural ending li ."),
    Tld(".lk", "Sri Lanka", "Sri Lanka", ""),
    Tld(".lr", "Liberia", "Liberia", ""),
    Tld(".ls", "Lesotho", "Lesotho", ""),
    Tld(".lt", "Lithuania", "Lithuania", ""),
    Tld(".lu", "Luxembourg", "Luxembourg", "Also unofficially used in Lucerne, Switzerland"),
    Tld(".lv", "Latvia", "Latvia", ""),
    Tld(".ly", "Libya", "Libya", "Used unofficially as a domain hack for words ending in -ly."),
    Tld(".ma", "Morocco", "Maroc", ""),
    Tld(".mc", "Monaco", "Monaco", "Only for companies with a trademark registered in Monaco."),
    Tld(".md", "Moldova", "Moldova", "Restricted to individuals or companies with a physical address in Moldova."),
    Tld(".me", "Montenegro", "Montenegro", "Also unofficially used and marketed as a domain hack (for example love.me, meet.me, etc.)."),
    Tld(".mg", "Madagascar", "Madagascar", "Restricted to registration with a company in Madagascar"),
    Tld(".mh", "Marshall Islands", "Marshall", "Inactive"),
    Tld(".mk", "North Macedonia", "Makedonija", "Restricted to individuals and companies in European Union."),
    Tld(".ml", "Mali", "Mali", "Also used as a free domain service to the public."),
    Tld(".mm", "Myanmar", "Myanmar", ""),
    Tld(".mn", "Mongolia", "Mongolia", "The second-level domains .gov.mn, .org.mn, and .edu.mn are reserved for special use. See .mn for more information."),
    Tld(".mo", "Macau", "Macao", "Registrants must have a registered business in Macau, with the same name as the domain they wish to register."),
    Tld(".mp", "Northern Mariana Islands (United States)", "Marianas Pacific", ""),
    Tld(".mq", "Martinique (France)", "Martinique", ""),
    Tld(".mr", "Mauritania", "Mauritania", ""),
    Tld(".ms", "Montserrat (United Kingdom)", "Montserrat", "Also unofficially used for Microsoft-related domains."),
    Tld(".mt", "Malta", "Malta", ""),
    Tld(".mu", "Mauritius", "Mauritius", ""),
    Tld(".mv", "Maldives", "Maldives", ""),
    Tld(".mw", "Malawi", "Malawi", ""),
    Tld(".mx", "Mexico", "Mexico", ""),
    Tld(".my", "Malaysia", "Malaysia", "Restricted to registration by an individual or company in Malaysia"),
    Tld(".mz", "Mozambique", "Mozambique", ""),
    Tld(".na", "Namibia", "Namibia", ""),
    Tld(".nc", "New Caledonia (France)", "New Caledonia", "Restricted to companies that have a New Caledonian Business Registration Certificate or individuals living in New Caledonia for at least 6 months."),
    Tld(".ne", "Niger", "Niger", ""),
    Tld(".nf", "Norfolk Island", "Norfolk", ""),
    Tld(".ng", "Nigeria", "Nigeria", ""),
    Tld(".ni", "Nicaragua", "Nicaragua", ""),
    Tld(".nl", "Netherlands", "Netherlands", "First active country-code domain outside the US."),
    Tld(".no", "Norway", "Norway", "Businesses and professionals must be registered as an approved type of organization in the Brønnøysund Register Centre. Individual applicants must be of age (18 years) and be registered in Folkeregisteret. All applicants must have a Norwegian postal address."),
    Tld(".np", "Nepal", "Nepal", "All .np domains are free to register for individuals and registered businesses. Foreign businesses must provide proof of local presence in Nepal."),
    Tld(".nr", "Nauru", "Nauru", "Was previously used as a free domain service to the public as co.nr."),
    Tld(".nu", "Niue", "Niue", "Commonly used by Danish, Dutch, and Swedish websites, because in those languages \"nu\" means \"now\"."),
    Tld(".nz", "New Zealand", "New Zealand", ""),
    Tld(".om", "Oman", "Oman", "Registrant must have company or trademark registered in Oman as well as a local administrative contact."),
    Tld(".pa", "Panama", "Panama", "Some use in Pennsylvania"),
    Tld(".pe", "Peru", "Peru", "Also unofficially used for Private Equity-related businesses."),
    Tld(".pf", "French Polynesia (France)", "Polynésie française", "With Clipperton Island"),
    Tld(".pg", "Papua New Guinea", "Papua New Guinea", ""),
    Tld(".ph", "Philippines", "Philippines", ""),
    Tld(".pk", "Pakistan", "Pakistan", "Operated by PKNIC since 1992"),
    Tld(".pl", "Poland", "Poland", ""),
    Tld(".pm", "Saint-Pierre and Miquelon (France)", "Saint Pierre and Miquelon", "Restricted to individuals and companies in European Union, Switzerland, Norway, Iceland, and Liechtenstein."),
    Tld(".pn", "Pitcairn Islands (United Kingdom)", "Pitcairn", "As a part of a marketing campaign, Lionsgate used the TLD for some (now defunct) sites related to The Hunger Games franchise, presenting it as the \"official\" country code of the fictional nation of Panem; notable sites included thecapitol.pn and revolution.pn."),
    Tld(".pr", "Puerto Rico (United States)", "Puerto Rico", ""),
    Tld(".ps", "Palestine", "Palestine", "Jerusalem, West Bank and Gaza Strip."),
    Tld(".pt", "Portugal", "Portugal", ""),
    Tld(".pw", "Palau", "Pelew", ""),
    Tld(".py", "Paraguay", "Paraguay", ""),
    Tld(".qa", "Qatar", "Qatar", ""),
    Tld(".re", "Réunion (France)", "Réunion", "Restricted to individuals and companies in European Union, Switzerland, Norway, Iceland, and Liechtenstein."),
    Tld(".ro", "Romania", "Romania", ""),
    Tld(".rs", "Serbia", "Republika Srbija", "See also .срб (.srb in Cyrillic). Also unofficially used for Rust (programming language)-related domains."),
    Tld(".ru", "Russia", "Russia", "See also .su, still in use, and .рф, for IDN."),
    Tld(".rw", "Rwanda", "Rwanda", ""),
    Tld(".sa", "Saudi Arabia", "Saudi Arabia", "Registrant must have a registered trademark in Saudi Arabia matching the domain name to register or provide company incorporation documents of a company in Saudi Arabia or for personal registrations a copy of valid ID. A letter on the official letterhead of your organization addressed to SaudiNIC requesting the domain name registration is also required. Local administrative contact required. 2LD registrations rolled out in 2011."),
    Tld(".sb", "Solomon Islands", "Solomon Islands, British", ""),
    Tld(".sc", "Seychelles", "Seychelles", "Also unofficially used for Snapchat-related domains."),
    Tld(".sd", "Sudan", "Sudan", ""),
    Tld(".se", "Sweden", "Sverige", ""),
    Tld(".sg", "Singapore", "Singapore", "Also unofficially used in the Canton of St. Gallen, Switzerland"),
    Tld(".sh", "Saint Helena, Ascension and Tristan da Cunha (United Kingdom)", "Saint Helena", ""),
    Tld(".si", "Slovenia", "Slovenia", ""),
    Tld(".sk", "Slovakia", "Slovensko", "Restricted to individuals and companies in European Union, Switzerland, Norway, Iceland, and Liechtenstein."),
    Tld(".sl", "Sierra Leone", "Sierra Leone", ""),
    Tld(".sm", "San Marino", "San Marino", "Domain name must be same as company name or trademark."),
    Tld(".sn", "Senegal", "Senegal", "Registration allowed for companies only. Individuals are not allowed to register."),
    Tld(".so", "Somalia", "Somalia", "Relaunched on 1 November 2010."),
    Tld(".sr", "Suriname", "Suriname", ""),
    Tld(".ss", "South Sudan", "South Sudan", ""),
    Tld(".st", "São Tomé and Príncipe", "São Tomé", "Also unofficially used in South Tyrol (or province of Bozen, see .bz)."),
    Tld(".su", "Soviet Union", "Soviet Union", "Still in use. Also unofficially used by Student Unions."),
    Tld(".sv", "El Salvador", "Salvador", ""),
    Tld(".sx", "Sint Maarten (Kingdom of the Netherlands)", ".sm, .ma, and .mt already allocated; airport code is SXM", ""),
    Tld(".sy", "Syria", "Syria", ""),
    Tld(".sz", "Eswatini", "Swaziland", "Registration is restricted to Eswatini organizations with Eswatini Trading Licenses."),
    Tld(".tc", "Turks and Caicos Islands (United Kingdom)", "Turks and Caicos", "Also marketed in Turkey. The official abbreviation of 'Türkiye Cumhuriyeti' (Republic of Turkey) is TC."),
    Tld(".td", "Chad", "Tchad", "Available for registration to entities connected with Chad only."),
    Tld(".tf", "French Southern and Antarctic Lands", "Terres australes et antarctiques françaises", "Seldom used. Restricted to individuals and companies in European Union, Switzerland, Norway, Iceland, and Liechtenstein. The domain also sees frequent use for community-run sites related to the video game Team Fortress 2."),
    Tld(".tg", "Togo", "Togo", ""),
    Tld(".th", "Thailand", "Thai", ""),
    Tld(".tj", "Tajikistan", "Tajik", ""),
    Tld(".tk", "Tokelau", "Tokelau", "Also used as a free domain service to the public."),
    Tld(".tl", "East Timor", "Timor-Leste", "Old code .tp has been deactivated since 2015."),
    Tld(".tm", "Turkmenistan", "Turkmen", ""),
    Tld(".tn", "Tunisia", "Tunisia", "Currently being marketed as the unofficial domain for Tamil Nadu"),
    Tld(".to", "Tonga", "Tonga", "Often used unofficially for Torrent, Turin (Torino in Italian), Toronto, Tokyo, or Tocantins, and also as a domain hack in Slavic languages (to meaning it)."),
    Tld(".tr", "Turkey", "Turkey", ".ct.tr and .nc.tr used by Northern Cyprus"),
    Tld(".tt", "Trinidad and Tobago", "Trinidad and Tobago", ""),
    Tld(".tv", "Tuvalu", "Tuvalu", "Used as an abbreviation of television, the domain is currently operated by dotTV, a VeriSign company; the Tuvalu government owns twenty percent of the company."),
    Tld(".tw", "Taiwan", "Taiwan", "Registration allowed worldwide, local presence not required. In line with ISO 3166-1, IANA's official position is that \"TW\" is \"designated for use to represent Taiwan, Province of China\"."),
    Tld(".tz", "Tanzania", "Tanzania", "TLD registrations allowed as of July 2022, no local presence in Tanzania required."),
    Tld(".ua", "Ukraine", "Ukraina", ""),
    Tld(".ug", "Uganda", "Uganda", ""),
    Tld(".uk", "United Kingdom", "United Kingdom", "The ISO 3166-1 code for the United Kingdom is GB. UK is a specially reserved ISO 3166-1 code. However, the creation of the .uk TLD predates the ISO 3166-1 list of ccTLD and is the primary TLD for the United Kingdom."),
    Tld(".us", "United States of America", "United States", "Registrants must be United States citizens, residents, or organizations, or a foreign entity with a presence in the United States. Formerly commonly used by U.S. State and local governments, see also .gov TLD."),
    Tld(".uy", "Uruguay", "Uruguay", "2LD rollout began on 10 July 2012."),
    Tld(".uz", "Uzbekistan", "Uzbekistan", ""),
    Tld(".va", "Vatican City", "Vatican", "Limited to the official sites of the Holy See (including those of the Vatican City State)."),
    Tld(".vc", "Saint Vincent and the Grenadines", "Vincent", ""),
    Tld(".ve", "Venezuela", "Venezuela", "Registration is at the third level."),
    Tld(".vg", "British Virgin Islands (United Kingdom)", "Virgin Islands", ""),
    Tld(".vi", "United States Virgin Islands (United States)", "Virgin Islands", ""),
    Tld(".vn", "Vietnam", "Viet Nam", ""),
    Tld(".vu", "Vanuatu", "Vanuatu", ""),
    Tld(".wf", "Wallis and Futuna", "Wallis and Futuna", "Restricted to individuals and companies in European Union, Switzerland, Norway, Iceland, and Liechtenstein."),
    Tld(".ws", "Samoa", "Western Samoa", "Marketed for use in general Websites"),
    Tld(".ye", "Yemen", "Yemen", ""),
    Tld(".yt", "Mayotte", "Mayotte", "Restricted to individuals and companies in European Union, Switzerland, Norway, Iceland and Liechtenstein. Also unofficially used for YouTube-related domains."),
    Tld(".za", "South Africa", "Zuid-Afrika", ".za derives from the Dutch name of the country, even though Dutch is no longer an official language."),
    Tld(".zm", "Zambia", "Zambia", ""),
    Tld(".zw", "Zimbabwe", "Zimbabwe", ""),
];

fn main() {
    let args: Vec<_> = env::args().skip(1).collect();
    let output: Vec<_> = TLD_DATA
        .iter()
        .filter(|Tld(name, _, _, _)| {
            args.is_empty() || args.iter().any(|query| name.contains(query))
        })
        .collect();
    if output.is_empty() {
        println!("<NO HITS>");
        return;
    }
    let longest_entity = output
        .iter()
        .map(|Tld(_, entity, _, _)| entity.len())
        .max()
        .unwrap();
    for Tld(name, entity, explanation, _) in output {
        match writeln!(stdout(), "{name} {entity:longest_entity$} {explanation}") {
            Ok(_) => {}
            Err(e) if e.kind() == BrokenPipe => break,
            Err(_) => panic!("Failed it print D:"),
        }
    }
}
