[package]
name = "gen-strs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
#regex = "1.9.1"
regex-syntax = "0.6.29"
rand_regex = { version = "0.15.1", features = ["unicode"] }
