[package]
name = "dbg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
clap = {version = "4.3.17", features = ["derive"]}
anstream = "0.3.2"
owo-colors = "3.5.0"